pepe:
    resource: "@pepeBundle/Resources/config/routing.yml"
    prefix:   /

red:
    resource: "@redBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation
